travis:
  secure:
    BINSTAR_TOKEN: S7TvQuGdUlAT+El+Y/UDJoJ2/bhB+lU2h9IAjkCZotmDj8oYGIBlR2LRDWb9U96nqSHaq4lCUWQd5RmvYrDyINwLuXuJTA5kCUyeJGJjIxDjXll9/2cfPMKWe+6xTkv7ifBHiAhK52tBYkdbdif8ih6ZblNBLSr9nLuFx+nED8XeexbxQ7zvMdBeR9+ou+B0xSCdodyf5c0aqYbpb9v5ugWyf6Lwh4bpa9/ODVfmuWq6/iEh4saDIdaXVaArfbHhnC3qG6uLbdSuhi6Z7um2SyQVbEAuuwhC8Jq9hANlde96VZ/cU4JPRFA3bmnxAClU4McwVlmKsIDhiXGyNVRm13TwYw7XPiU7jjgg+7J57EZ7CT4xktrVxTAceNVPKWvwp4X0LjuMf0oiQr0jyvrP7/gcXf6+R7fzKcYv+bnVAwh1kifHP7af3rAfij65K64iQqzNK49sXPGOboQFlpKmpGB+C//7zwQS+huEypwV+BfsIgS1r+2VfmMAPov6OE9KUwtP6Pkab5nGtur1Mz7Y2dBmIDc/PpFhWW8YF/mTYMfFS18rScmHVZG/hTbQTlgeI7KBvk4SKWRoZAtE4s/SbW9r+sd4fwqnJ4L556/dZYUIDgfwQ4lZ6cIetGWjvwsoiCEFeVPI9yvAHADpsq/ZTe94noSdTDE8A+DBN0ouz6w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
